# Generated by Django 4.2.2 on 2023-06-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jkkonline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kitab', models.CharField(max_length=255)),
                ('harga_barang', models.CharField(max_length=255)),
            ],
        ),
    ]
